### PR TITLE
Fixed kubevirt-tutorial-presubmit-lab-testing-k8s-1.13.3

### PR DESCRIPTION
**Pull request by ansijain**
Signed-off-by: ansijain <ansi.jain@india.nec.com>

### CODE REVIEW

**Comment by ansijain** [comment]
Fixes https://github.com/kubevirt/kubevirt-tutorial/issues/119

**Comment by mazzystr** [comment]
Thank you for finding and fixing this

/lgtm
/approve

**Comment by rmohr** [comment]
@mazzystr I guess the k8s version should be bumped here. 1.13 is really old :/

**Pull request merged**
