### PR TITLE
Enable nested before deploying

### PR DESCRIPTION
**Pull request by iranzo**

### CODE REVIEW

**Comment by codificat** [comment]
Do we need this?  AFAIK we've been able to spin VMs just fine with nested virt so far - which should perform quite better than emulation.

The environment setup code includes [enabling nested virt](https://github.com/kubevirt/kubevirt-tutorial/blob/669dbfa6ba4e75c88e1a0f2240f7cca66016ef2b/administrator/ansible/roles/common/tasks/common.yml#L41).

**Comment by iranzo** [comment]
This is to test the failure in CI in #108 to see if the timeout in lab4 happens because of vm spin as the commit in that PR should have nothing to do at all with infra failing, but it does

**Comment by iranzo** [comment]
If this test passes, means that nested is 'now' needed for another reason and might, via merge, enable us to pass 108 and merge it

**Comment by codificat** [comment]
I see... however, if CI is broken let's rather fix the CI, no?

My understanding is that with this change the labs would run slower, right?

**Pull request closed without merging**
